Use docker for acceptance tests

diff --git a/templates/init.erb b/templates/init.erb
--- a/templates/init.erb
+++ b/templates/init.erb
@@ -24,82 +24,76 @@ BUNDLE_PREFIX=""
 <% end -%>
 RVM_PREFIX="<%= @rvm_prefix %>"
 
-DAEMON_OPTS="-C $APP_ROOT/config/puma.rb"
-PID_PATH="$APP_ROOT/tmp/pids"
-SOCKET_PATH="$APP_ROOT/tmp/sockets"
-WEB_SERVER_PID="$PID_PATH/puma.pid"
+SOCKET_PATH="$APP_ROOT/tmp/sockets/puma.socket"
+PID_PATH="$APP_ROOT/tmp/pids/puma.pid"
 NAME="<%= @app_name %>"
 DESC="<%= @app_name %>"
 
-check_pid(){
-  if [ -f $WEB_SERVER_PID ]; then
-    PID=`cat $WEB_SERVER_PID`
-    STATUS=`ps aux | grep $PID | grep -v grep | wc -l`
-  else
-    STATUS=0
-    PID=0
-  fi
+check_pid() {
+    if [ -f $PID_PATH ]; then
+        PID=`cat $PID_PATH`
+        STATUS=`ps aux | grep $PID | grep -v grep | wc -l`
+    else
+        STATUS=0
+        PID=0
+    fi
 }
 
 execute() {
-  sudo -u $APP_USER -H bash -l -c "$RVM_PREFIX$1"
+    echo "su $APP_USER --login -s /bin/bash -l -c $RVM_PREFIX$1"
+    su $APP_USER --login -s /bin/bash -l -c "$RVM_PREFIX$1"
 }
 
 start() {
-  cd $APP_ROOT
-  check_pid
-  if [ "$PID" -ne 0 -a "$STATUS" -ne 0 ]; then
-    # Program is running, exit with error code 1.
-    echo "Error! $DESC $NAME is currently running!"
-    exit 1
-  else
-    if [ `whoami` = root ]; then
-        if [ -f "$SOCKET_PATH/puma.socket"]; then
-            execute "rm $SOCKET_PATH/puma.socket"
+    cd $APP_ROOT
+    check_pid
+    if [ "$PID" -ne 0 -a "$STATUS" -ne 0 ]; then
+        echo "Error! $NAME is currently running!"
+        exit 1
+    else
+        if [ `whoami` = root ]; then
+            [[ -f $SOCKET_PATH ]] && execute "rm $SOCKET_PATH"
+            execute "RAILS_ENV=production$BUNDLE_PREFIX puma -C $APP_ROOT/config/puma.rb"
+            echo "$NAME started"
         fi
-        execute "RAILS_ENV=production$BUNDLE_PREFIX puma $DAEMON_OPTS"
-        echo "$DESC started"
     fi
-  fi
 }
 
 stop() {
-  cd $APP_ROOT
-  check_pid
-  if [ "$PID" -ne 0 -a "$STATUS" -ne 0 ]; then
-    ## Program is running, stop it.
-    kill -QUIT `cat $WEB_SERVER_PID`
-    rm "$WEB_SERVER_PID" >> /dev/null
-    echo "$DESC stopped"
-  else
-    ## Program is not running, exit with error.
-    echo "Error! $DESC not started!"
-    exit 1
-  fi
+    cd $APP_ROOT
+    check_pid
+    if [ "$PID" -ne 0 -a "$STATUS" -ne 0 ]; then
+        kill -QUIT `cat $PID_PATH`
+        [[ -f $PID_PATH ]] && rm $PID_PATH > /dev/null
+        echo "$NAME stopped!"
+    else
+        echo "Error! $NAME not started!"
+        exit 1
+    fi
 }
 
 restart() {
-  cd $APP_ROOT
-  check_pid
-  if [ "$PID" -ne 0 -a "$STATUS" -ne 0 ]; then
-    echo "Restarting $DESC..."
-    kill -USR2 `cat $WEB_SERVER_PID`
-    echo "$DESC restarted."
-  else
-    echo "Error, $NAME not running!"
-    exit 1
-  fi
+    cd $APP_ROOT
+    check_pid
+    if [ "$PID" -ne 0 -a "$STATUS" -ne 0 ]; then
+        echo "Restarting $NAME ..."
+        kill -USR2 `cat $PID_PATH`
+        echo "$NAME restarted."
+    else
+        echo "Error, $NAME not running!"
+        exit 1
+    fi
 }
 
 status() {
-  cd $APP_ROOT
-  check_pid
-  if [ "$PID" -ne 0 -a "$STATUS" -ne 0 ]; then
-    echo "$DESC / Puma with PID $PID is running."
-  else
-    echo "$DESC is not running."
-    exit 1
-  fi
+    cd $APP_ROOT
+    check_pid
+    if [ "$PID" -ne 0 -a "$STATUS" -ne 0 ]; then
+        echo "$NAME / Puma with PID $PID is running."
+    else
+        echo "$NAME is not running."
+        exit 1
+    fi
 }
 
 ## Check to see if we are running as root first.
@@ -110,25 +104,25 @@ if [ "$(id -u)" != "0" ]; then
 fi
 
 case "$1" in
-  start)
+    start)
         start
         ;;
-  stop)
+    stop)
         stop
         ;;
-  restart)
+    restart)
         restart
         ;;
-  reload|force-reload)
+    reload|force-reload)
         echo -n "Reloading $NAME configuration: "
         kill -HUP `cat $PID`
         echo "done."
         ;;
-  status)
+    status)
         status
         ;;
-  *)
-        echo "Usage: sudo service gitlab {start|stop|restart|reload}" >&2
+    *)
+        echo "Usage: sudo service $NAME {start|stop|restart|reload}" >&2
         exit 1
         ;;
 esac
